---
- name: Playbook to PXE Setup
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - /ansible/salt-master/secrets.yml
  vars:
    ansible_become_pass: "{{ sudo_password }}"
  tasks:
    - name: Create a new folder
      file:
        path: /path/to/newfolder
        state: directory
        mode: '0755'

    - name: Copy the file
      copy:
        src: /path/to/source/file.tar.gz
        dest: /path/to/newfolder/

    - name: Extract the tar file
      unarchive:
        src: /path/to/newfolder/file.tar.gz
        dest: /path/to/newfolder/
        remote_src: yes

    - name: Run the bash script
      command: /bin/bash /path/to/newfolder/your_script.sh
      args:
        chdir: /path/to/newfolder/
